export const UI_EN: Record<string, { text?: string; title?: string; placeholder?: string; aria?: string }> = {
  settingsTitle: { text: 'Settings' },
  tabBtnGeneral: { text: 'General' },
  tabBtnButtons: { text: 'Buttons' },
  tabBtnAppearance: { text: 'Theme' },
  showHintsLabel: { text: 'Show hints' },
  autoStyleMenuLabel: { text: 'Auto-open style menu' },
  penTouchModeLabel: { text: 'Pen mode: limit touch' },
  penTouchAllowZoomLabel: { text: 'Zoom gestures' },
  penTouchAllowPanLabel: { text: 'Pan gestures' },
  penTouchAllowButtonsLabel: { text: 'Allow button taps' },
  languageLabel: { text: 'Language' },
  exportConfigText: { text: 'Export configuration' },
  importConfigText: { text: 'Import configuration' },
  settingsCloseBtn: { title: 'Close', aria: 'Close' },
  settingsBtn: { title: 'Settings', aria: 'Settings' },
  helpBtn: { title: 'Help', aria: 'Help' },
  modeMove: { title: 'Select', aria: 'Select' },
  modeMultiselect: { title: 'Multiselect', aria: 'Multiselect' },
  modeLabel: { title: 'Label', aria: 'Label' }
};

// Additional settings translations
Object.assign(UI_EN, {
  precisionTitle: { text: 'Measurement precision' },
  precisionLengthLabel: { text: 'Lengths:' },
  precisionAngleLabel: { text: 'Angles:' },
  exportImportTitle: { text: 'Export & Import' },
  exportImportDesc: { text: 'Save or load the full application configuration.' },
  themeDarkText: { text: 'Dark' },
  themeLightText: { text: 'Light' },
  defaultColorsTitle: { text: 'Default colors' },
  themeBgLabel: { text: 'Background color:' },
  themePanelLabel: { text: 'Panel color:' },
  themeStrokeLabel: { text: 'Line color:' },
  themeHighlightLabel: { text: 'Highlight color:' },
  themeSelectionLineStyleLabel: { text: 'Selection line style:' },
  themeSelectionEffectLabel: { text: 'Selection effect:' },
  themeHighlightWidthLabel: { text: 'Selection width:' },
  themeSelectionPointStyleSameAsLine: { text: 'Point style same as line:' },
  themeSelectionPointRadiusLabel: { text: 'Point selection radius:' }
});

Object.assign(UI_EN, {
  previewTitle: { text: 'Preview' },
  defaultSizesTitle: { text: 'Default sizes' },
  themeLineWidthLabel: { text: 'Line width:' },
  themePointSizeLabel: { text: 'Point size:' },
  themeArcRadiusLabel: { text: 'Angle arc radius:' },
  themeLabelFontSize: { text: 'Label font size:' }
});

Object.assign(UI_EN, {
  styleMenu: { title: 'Selection style', aria: 'Selection style' },
  viewVerticesOption: { title: 'Vertices', aria: 'Vertices' },
  viewEdgesOption: { title: 'Edges', aria: 'Edges' },
  styleTickToggle: { title: 'Tick marker', aria: 'Tick marker' },
  rayLeftOption: { title: 'Left ray', aria: 'Left ray' },
  rayRightOption: { title: 'Right ray', aria: 'Right ray' },
  raySegmentOption: { title: 'Segment', aria: 'Segment' },
  viewCirclePointsOption: { title: 'Points', aria: 'Points' },
  viewCircleLineOption: { title: 'Circle', aria: 'Circle' },
    customColorBtn: { title: 'Other color', aria: 'Other color' },
    pointHollowToggleBtn: { title: 'Hollow point', aria: 'Hollow point' },
    exteriorAngleBtn: { title: 'Reflex angle', aria: 'Reflex angle' },
    fillToggleBtn: { title: 'Fill', aria: 'Fill' },
    polygonLockToggleBtn: { title: 'Lock shape', aria: 'Lock shape' },
    labelGreekToggle: { title: 'Symbol keyboard', aria: 'Symbol keyboard' },
  labelFontDecrease: { title: 'Decrease text size', aria: 'Decrease text size' },
  labelFontIncrease: { title: 'Increase text size', aria: 'Increase text size' },
  labelAlignToggle: { title: 'Label alignment (left/center)', aria: 'Label alignment' },
  labelGreekShift: { title: 'Uppercase', aria: 'Uppercase' },
  labelScriptToggle: { title: 'Latin script', aria: 'Latin script' },
  lineWidthDecrease: { title: 'Decrease width', aria: 'Decrease width' },
  lineWidthIncrease: { title: 'Increase width', aria: 'Increase width' },
  angleRadiusDecreaseBtn: { title: 'Decrease arc radius', aria: 'Decrease arc radius' },
  angleRadiusIncreaseBtn: { title: 'Increase arc radius', aria: 'Increase arc radius' },
  rightAngleBtn: { title: 'Right angle', aria: 'Right angle' },
  pointLabelsAutoBtn: { title: 'Auto-align labels', aria: 'Auto-align labels' },
  pointLabelsAwayBtn: { title: 'Move labels away', aria: 'Move labels away' },
  pointLabelsCloserBtn: { title: 'Move labels closer', aria: 'Move labels closer' },
  labelToolsOverflowBtn: { title: 'More', aria: 'More' },
  eraserBtn: { title: 'Eraser', aria: 'Eraser' },
  hideButton: { title: 'Hide/Show selection', aria: 'Hide/Show selection' },
  copyStyleBtn: { title: 'Copy/Paste style', aria: 'Copy/Paste style' },
  multiMoveBtn: { title: 'Move selection', aria: 'Move selection' },
  multiHideBtn: { title: 'Hide selection', aria: 'Hide selection' },

  multiCloneBtn: { title: 'Clone selection', aria: 'Clone selection' },
  cloudFilesBtn: { title: 'Cloud files', aria: 'Cloud files' },
  exportJsonBtn: { title: 'Save (Ctrl)', aria: 'Save (Ctrl)' },
  bundlePrevBtn: { title: 'Previous file', aria: 'Previous file' },
  bundleNextBtn: { title: 'Next file', aria: 'Next file' },
  deletePoint: { title: 'Delete selected', aria: 'Delete selected' },
  undo: { title: 'Undo', aria: 'Undo' },
  redo: { title: 'Redo', aria: 'Redo' },
  zoomMenu: { title: 'Options', aria: 'Options' },
  clearAll: { title: 'Clear all', aria: 'Clear all' },
  showHiddenBtn: { title: 'Show hidden', aria: 'Show hidden' },
  showMeasurementsBtn: { title: 'Show measurements', aria: 'Show measurements' },
  copyImageBtn: { title: 'Copy image (PNG)', aria: 'Copy image' },
  saveImageBtn: { title: 'Save PNG', aria: 'Save PNG' },
  invertColorsBtn: { title: 'Invert colors', aria: 'Invert colors' },
  debugToggle: { title: 'Object list', aria: 'Debug' },
  settingsBtn: { title: 'Settings', aria: 'Settings' },
  helpBtn: { title: 'Help', aria: 'Help' },
  themeDark: { title: 'Dark mode', aria: 'Dark mode' },
  debugCloseBtn: { title: 'Close debug panel', aria: 'Close debug panel' },
  cloudCloseBtn: { title: 'Close files panel', aria: 'Close files panel' },
  settingsCloseBtn: { title: 'Close', aria: 'Close' },
  exportConfigBtn: { title: 'Export configuration', aria: 'Export configuration' },
  importConfigBtn: { title: 'Import configuration', aria: 'Import configuration' },
  pointStyleToggleBtn: { title: 'Point style', aria: 'Point style' },

  // mode buttons
  modeMove: { title: 'Select', aria: 'Select' },
  modeMultiselect: { title: 'Multiselect', aria: 'Multiselect' },
  modeLabel: { title: 'Label', aria: 'Label' },
  modeAdd: { title: 'Add point', aria: 'Point' },
  modeSegment: { title: 'Segment', aria: 'Segment' },
  modeParallel: { title: 'Parallel', aria: 'Parallel' },
  modePerpendicular: { title: 'Perpendicular', aria: 'Perpendicular' },
  modeCircle: { title: 'Circle', aria: 'Circle' },
  modeCircleThree: { title: 'Circle through 3 points', aria: 'Circle through 3 points' },
  modeTriangleUp: { title: 'Regular triangle', aria: 'Regular triangle' },
  modeSquare: { title: 'Square', aria: 'Square' },
  modePolygon: { title: 'Polygon', aria: 'Polygon' },
  modeNgon: { title: 'n-gon', aria: 'n-gon' },
  modeAngle: { title: 'Angle', aria: 'Angle' },
  modeBisector: { title: 'Bisector', aria: 'Bisector' },
  modeMidpoint: { title: 'Midpoint', aria: 'Midpoint' },
  modeSymmetric: { title: 'Symmetric point', aria: 'Symmetric point' },
  modeTangent: { title: 'Tangent', aria: 'Tangent' },
  modePerpBisector: { title: 'Perpendicular bisector', aria: 'Perpendicular bisector' },
  modeHandwriting: { title: 'Handwriting', aria: 'Handwriting' }
});

export default UI_EN;
