export const UI_PL: Record<string, { text?: string; title?: string; placeholder?: string; aria?: string }> = {
  settingsTitle: { text: 'Konfiguracja' },
  tabBtnGeneral: { text: 'Ogólne' },
  tabBtnButtons: { text: 'Przyciski' },
  tabBtnAppearance: { text: 'Wygląd' },
  showHintsLabel: { text: 'Pokaż podpowiedzi' },
  languageLabel: { text: 'Język' },
  exportConfigText: { text: 'Eksportuj konfigurację' },
  importConfigText: { text: 'Importuj konfigurację' },
  settingsCloseBtn: { title: 'Zamknij', aria: 'Zamknij' },
  settingsBtn: { title: 'Konfiguracja', aria: 'Konfiguracja' },
  helpBtn: { title: 'Pomoc', aria: 'Pomoc' },
  modeMove: { title: 'Zaznacz', aria: 'Zaznacz' },
  modeMultiselect: { title: 'Zaznacz wiele', aria: 'Zaznacz wiele' },
  modeLabel: { title: 'Etykieta', aria: 'Etykieta' }
};

// Additional settings translations
Object.assign(UI_PL, {
  precisionTitle: { text: 'Precyzja wymiarów' },
  precisionLengthLabel: { text: 'Długości:' },
  precisionAngleLabel: { text: 'Kątów:' },
  exportImportTitle: { text: 'Eksport i Import' },
  exportImportDesc: { text: 'Zapisz lub wczytaj pełną konfigurację aplikacji.' },
  themeDarkText: { text: 'Ciemny' },
  themeLightText: { text: 'Jasny' },
  defaultColorsTitle: { text: 'Domyślne kolory' },
  themeBgLabel: { text: 'Kolor tła:' },
  themePanelLabel: { text: 'Kolor okna:' },
  themeStrokeLabel: { text: 'Kolor linii:' },
  themeHighlightLabel: { text: 'Kolor zaznaczenia:' },
  themeSelectionLineStyleLabel: { text: 'Styl linii zaznaczenia:' },
  themeSelectionEffectLabel: { text: 'Efekt zaznaczenia:' },
  themeHighlightWidthLabel: { text: 'Szerokość zaznaczenia:' },
  themeSelectionPointStyleSameAsLine: { text: 'Styl punktu jak linii:' },
  themeSelectionPointRadiusLabel: { text: 'Promień zaznaczenia punktu:' }
});

Object.assign(UI_PL, {
  previewTitle: { text: 'Podgląd' },
  defaultSizesTitle: { text: 'Domyślne rozmiary' },
  themeLineWidthLabel: { text: 'Grubość linii:' },
  themePointSizeLabel: { text: 'Rozmiar punktu:' },
  themeArcRadiusLabel: { text: 'Promień łuku kąta:' },
  themeLabelFontSize: { text: 'Rozmiar czcionki etykiet:' }
});

Object.assign(UI_PL, {
  styleMenu: { title: 'Styl zaznaczenia', aria: 'Styl zaznaczenia' },
  viewVerticesOption: { title: 'Wierzchołki', aria: 'Wierzchołki' },
  viewEdgesOption: { title: 'Krawędzie', aria: 'Krawędzie' },
  styleTickToggle: { title: 'Znacznik zgodności', aria: 'Znacznik zgodności' },
  rayLeftOption: { title: 'Lewa półprosta', aria: 'Lewa półprosta' },
  rayRightOption: { title: 'Prawa półprosta', aria: 'Prawa półprosta' },
  raySegmentOption: { title: 'Odcinek', aria: 'Odcinek' },
  viewCirclePointsOption: { title: 'Punkty', aria: 'Punkty' },
  viewCircleLineOption: { title: 'Okrąg', aria: 'Okrąg' },
  customColorBtn: { title: 'Inny kolor', aria: 'Inny kolor' },
  pointHollowToggleBtn: { title: 'Pusty punkt', aria: 'Pusty punkt' },
  exteriorAngleBtn: { title: 'Kąt wklęsły', aria: 'Kąt wklęsły' },
  fillToggleBtn: { title: 'Wypełnienie', aria: 'Wypełnienie' },
  labelGreekToggle: { title: 'Klawiatura symboli', aria: 'Klawiatura symboli' },
  labelFontDecrease: { title: 'Zmniejsz rozmiar tekstu', aria: 'Zmniejsz rozmiar tekstu' },
  labelFontIncrease: { title: 'Zwiększ rozmiar tekstu', aria: 'Zwiększ rozmiar tekstu' },
  labelAlignToggle: { title: 'Wyrównanie etykiety (lewo / środek)', aria: 'Wyrównanie etykiety' },
  labelGreekShift: { title: 'Wielkie litery', aria: 'Wielkie litery' },
  labelScriptToggle: { title: 'Latin script', aria: 'Latin script' },
  lineWidthDecrease: { title: 'Zmniejsz grubość', aria: 'Zmniejsz grubość' },
  lineWidthIncrease: { title: 'Zwiększ grubość', aria: 'Zwiększ grubość' },
  angleRadiusDecreaseBtn: { title: 'Zmniejsz promień łuku', aria: 'Zmniejsz promień łuku' },
  angleRadiusIncreaseBtn: { title: 'Zwiększ promień łuku', aria: 'Zwiększ promień łuku' },
  rightAngleBtn: { title: 'Kąt prosty', aria: 'Kąt prosty' },
  pointLabelsAutoBtn: { title: 'Wyrównaj etykiety', aria: 'Wyrównaj etykiety' },
  pointLabelsAwayBtn: { title: 'Odsuń etykiety', aria: 'Odsuń etykiety' },
  pointLabelsCloserBtn: { title: 'Przysuń etykiety', aria: 'Przysuń etykiety' },
  labelToolsOverflowBtn: { title: 'Więcej', aria: 'Więcej' },
  eraserBtn: { title: 'Gumka', aria: 'Gumka' },
  hideButton: { title: 'Ukryj/Pokaż zaznaczone', aria: 'Ukryj/Pokaż zaznaczone' },
  copyStyleBtn: { title: 'Kopiuj/Wklej styl', aria: 'Kopiuj/Wklej styl' },
  multiMoveBtn: { title: 'Przesuń zaznaczone', aria: 'Przesuń zaznaczone' },
  multiCloneBtn: { title: 'Klonuj zaznaczone', aria: 'Klonuj zaznaczone' },
  cloudFilesBtn: { title: 'Pliki w chmurze', aria: 'Pliki w chmurze' },
  exportJsonBtn: { title: 'Zapisz (CTR)', aria: 'Zapisz (CTR)' },
  bundlePrevBtn: { title: 'Poprzedni plik', aria: 'Poprzedni plik' },
  bundleNextBtn: { title: 'Następny plik', aria: 'Następny plik' },
  deletePoint: { title: 'Usuń zaznaczone', aria: 'Usuń zaznaczone' },
  undo: { title: 'Cofnij', aria: 'Cofnij' },
  redo: { title: 'Ponów', aria: 'Ponów' },
  zoomMenu: { title: 'Opcje', aria: 'Opcje' },
  clearAll: { title: 'Wyczyść wszystko', aria: 'Wyczyść wszystko' },
  showHiddenBtn: { title: 'Pokaż ukryte', aria: 'Pokaż ukryte' },
  showMeasurementsBtn: { title: 'Pokaż wymiary', aria: 'Pokaż wymiary' },
  copyImageBtn: { title: 'Kopiuj obraz (PNG)', aria: 'Kopiuj obraz' },
  saveImageBtn: { title: 'Zapisz PNG', aria: 'Zapisz PNG' },
  invertColorsBtn: { title: 'Odwróć kolory', aria: 'Odwróć kolory' },
  debugToggle: { title: 'Lista obiektów', aria: 'Debug' },
  settingsBtn: { title: 'Konfiguracja', aria: 'Konfiguracja' },
  helpBtn: { title: 'Pomoc', aria: 'Pomoc' },
  themeDark: { title: 'Tryb ciemny', aria: 'Tryb ciemny' },
  debugCloseBtn: { title: 'Zamknij panel debug', aria: 'Zamknij panel debug' },
  cloudCloseBtn: { title: 'Zamknij panel plików', aria: 'Zamknij panel plików' },
  settingsCloseBtn: { title: 'Zamknij', aria: 'Zamknij' },
  exportConfigBtn: { title: 'Eksportuj konfigurację', aria: 'Eksportuj konfigurację' },
  importConfigBtn: { title: 'Importuj konfigurację', aria: 'Importuj konfigurację' },
  pointStyleToggleBtn: { title: 'Styl punktów', aria: 'Styl punktów' },

  // mode buttons
  modeMove: { title: 'Zaznacz', aria: 'Zaznacz' },
  modeMultiselect: { title: 'Zaznacz wiele', aria: 'Zaznacz wiele' },
  modeLabel: { title: 'Etykieta', aria: 'Etykieta' },
  modeAdd: { title: 'Dodaj punkt', aria: 'Punkt' },
  modeSegment: { title: 'Odcinek', aria: 'Odcinek' },
  modeParallel: { title: 'Równoległa', aria: 'Równoległa' },
  modePerpendicular: { title: 'Prostopadła', aria: 'Prostopadła' },
  modeCircle: { title: 'Okrąg', aria: 'Okrąg' },
  modeCircleThree: { title: 'Okrąg przez 3 punkty', aria: 'Okrąg przez 3 punkty' },
  modeTriangleUp: { title: 'Trójkąt foremny', aria: 'Trójkąt foremny' },
  modeSquare: { title: 'Kwadrat', aria: 'Kwadrat' },
  modePolygon: { title: 'Wielokąt', aria: 'Wielokąt' },
  modeNgon: { title: 'n-gon', aria: 'n-gon' },
  modeAngle: { title: 'Kąt', aria: 'Kąt' },
  modeBisector: { title: 'Dwusieczna', aria: 'Dwusieczna' },
  modeMidpoint: { title: 'Punkt środkowy', aria: 'Punkt środkowy' },
  modeSymmetric: { title: 'Punkt symetryczny', aria: 'Punkt symetryczny' },
  modeTangent: { title: 'Styczna', aria: 'Styczna' },
  modePerpBisector: { title: 'Symetralna', aria: 'Symetralna' },
  modeHandwriting: { title: 'Pismo odręczne', aria: 'Pismo odręczne' }
});

export default UI_PL;
